# Generated by Django 4.0 on 2021-12-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('questions', models.TextField()),
                ('answer', models.TextField()),
                ('ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('info', models.TextField(default=None)),
                ('cost', models.IntegerField(default=0)),
                ('count_in_stock', models.IntegerField(default=100000000)),
                ('count_sold', models.IntegerField(default=0)),
                ('image', models.ImageField(default=None, null=None, upload_to='way_to_budy/images/goods')),
                ('file', models.FileField(default=None, null=None, upload_to='way_to_budy/files')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('choose', 'choose'), ('answer', 'answer')], max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('text', models.TextField(default='')),
                ('ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='way_to_budy.form')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInformationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
